using UnityEngine;
using UnityEngine.UI;

namespace StressLevelZero.UI
{
	public class Control_UI_HappyBand : MonoBehaviour
	{
		public float recheck_t;
		public bool isActive;
		public Control_Character ctrl_character;
		public bool disp_Health;
		public bool disp_Strength;
		public bool disp_Speed;
		public bool disp_Endurance;
		public bool disp_Water;
		public bool disp_Food;
		public bool disp_Experience;
		public bool disp_Jump;
		public bool disp_Focus;
		public bool disp_TUD;
		public bool disp_Additional;
		public Color color_Health;
		public Color color_flash_Health;
		public GameObject panel_Health;
		public GameObject bar_cur_Health;
		public GameObject bar_tar_Health;
		public GameObject[] ticks_Health;
		public float flash_Health_t;
		public Text text_cur_Health;
		public Text text_lvl_Health;
		public Text text_lvl_reg_Health;
		public bool disp_color_Strength;
		public Color color_Strength;
		public GameObject panel_Strength;
		public Text text_Strength;
		public Text text_lvl_Strength;
		public Color color_Speed;
		public GameObject panel_Speed;
		public GameObject bar_cur_Speed;
		public Text text_Speed;
		public Text text_lvl_Speed;
		public Text text_max_Speed;
		public Color color_Endurance;
		public Color color_flash_Endurance;
		public GameObject panel_Endurance;
		public GameObject bar_blood_Oxygen;
		public float flash_Endurance_t;
		public Text text_BPM;
		public Image image_BPM;
		public Text text_Arm_L;
		public Text text_Arm_R;
		public Text text_Legs;
		public Text text_BO_Percent;
		public Color color_Water;
		public Color color_flash_Water;
		public GameObject panel_Water;
		public GameObject bar_cur_Water;
		public GameObject bar_tar_Water;
		public GameObject[] ticks_Water;
		public float flash_Water_t;
		public Text text_cur_Water;
		public Text text_lvl_Water;
		public Color color_Food;
		public Color color_flash_Food;
		public GameObject panel_Food;
		public GameObject bar_cur_Food;
		public GameObject bar_tar_Food;
		public GameObject[] ticks_Food;
		public float flash_Food_t;
		public Text text_cur_Food;
		public Text text_lvl_Food;
		public Color color_Jump;
		public GameObject panel_Jump;
		public GameObject bar_force_Jump;
		public Text text_lvl_Jump;
		public Text text_mod_Jump;
		public Color color_Focus;
		public Color color_intensity_Focus;
		public GameObject panel_Focus;
		public GameObject bar_cur_dur_Focus;
		public bool dur_AutoRegen;
		public float tru_max_int_Focus;
		public Text text_lvl_dur_Focus;
		public Text text_lvl_int_Focus;
		public Text text_AutoRegen_Focus;
		public Color color_TUD;
		public GameObject panel_TUD;
		public GameObject bar_cur_TUD;
		public Text text_lvl_TUD;
		public GameObject image_currently_Dying;
		public Color color_Black;
	}
}
